### ISSUE TITLE
Not working at all on any of the videos

### ISSUE THREAD

**Issue by rsingh2083** [kenil-shah/Description-Based-Person-Identification#1]
I ran app.py and selected lots of combinations for torso and male/female but I didnt get any output or boxes in the output video at all. I downloaded these video and tried your code. Didnt get any thing at all !!
https://www.youtube.com/watch?v=9lnPqbgEU7o
https://www.youtube.com/watch?v=NyLF8nHIquM
https://www.youtube.com/watch?v=NyLF8nHIquM

**Comment by Vanditg** [comment]
Dear @rsingh2083 
Thank you for looking at our work! I kindly request you to please have a look at our 2nd implementation and I had to make sure that the person retrieval based on query will get detected from your input videos. 
Code - shorturl.at/cltC0

If you have doubts let us know!
